In [3]:
import numpy as np
arr =np.zeros((2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
print("shape",arr.shape)
print("size",arr.size)
print("Data type",arr.dtype)

shape (2, 4)
size 8
Data type float64


In [7]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
a = np.array([[1,3],[2,3],[3,4]])
print(a)

[[1 3]
 [2 3]
 [3 4]]


In [10]:
print(a.shape)
print(a.size)
print(a.dtype)

(3, 2)
6
int32


In [12]:
la = np.linspace(0,10,5)
print(la)

[ 0.   2.5  5.   7.5 10. ]


In [15]:
array = np.arange(0,10,2)
print("range",array)


range [0 2 4 6 8]


In [16]:
b=np.array([1,2,3,4,5])
c=np.array([1,2,3,4,5])
add = b+c
print(add)

[ 2  4  6  8 10]


In [17]:
mul = a*2
print(mul)

[[2 6]
 [4 6]
 [6 8]]


In [22]:
sl = c[::-1]
print(sl)

[5 4 3 2 1]


In [2]:
import numpy as np
id = np.eye(4,4)
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
import numpy as np
a=np.array([[1,2,4],[3,4,6],[4,3,5]])
print(a)

[[1 2 4]
 [3 4 6]
 [4 3 5]]


In [16]:
np.sort(a,kind="mergesort")

array([[1, 2, 4],
       [3, 4, 6],
       [3, 4, 5]])

In [19]:
np.random.random(4)

array([0.46358122, 0.0436967 , 0.22135177, 0.93810768])

In [20]:
np.random.random(size=3)

array([0.29055065, 0.04658676, 0.631421  ])