In [1]:
import numpy as np

In [3]:
array = np.array([1,2,3]) 
print(array)

[1 2 3]


In [8]:
#multi-dimentional
array = np.array([[[1,2,3],
                  [4,5,6],
                  [8,9,0]]])
print(array)

[[[1 2 3]
  [4 5 6]
  [8 9 0]]]


In [10]:
print(array.ndim)
print(array.shape)
print(array[0,0,1])

3
(1, 3, 3)
2


In [13]:
#slicing
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr1[0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(arr1[::-1])
print(arr1[::-2])

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[7 8 9]
 [1 2 3]]


In [19]:
#column
print(arr1[:,0:2])
print(arr1[:,::-1])

[[1 2]
 [4 5]
 [7 8]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [18]:
print(arr1[0:2,0:2])

[[1 2]
 [4 5]]


In [20]:
#scalar arithemetic
arr2 = np.array([1,2,3])
print(arr2 +1)
print(arr2 -2)
print(arr2 *3)
print(arr2 /4)
print(arr2 ** 2)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[1 4 9]


In [24]:
#vectorized math func
arr3 = np.array([1.02,0.34,8.23])
print(np.sqrt(arr3))
print(np.round(arr3))

[1.00995049 0.58309519 2.86879766]
[1. 0. 8.]


In [25]:
#cal area
arr4 = np.array([1,2,3])
print(np.pi*arr4**2)

[ 3.14159265 12.56637061 28.27433388]


In [27]:
arr4 = np.array([1,2,3])
arr5 = np.array([4,5,6])
print(arr4+arr5)
print(arr4-arr5)
print(arr4*arr5)
print(arr4/arr5)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [35]:
#comparsion operators
arr6 = np.array([91,55,66,77,33,90])
print(arr6 == 90)
print(arr6 < 70)

[False False False False False  True]
[False  True  True False  True False]


In [34]:
arr6[arr6 < 90] = 0
print(arr6)

[91  0  0  0  0 90]


In [40]:
#boardcasting
arr0= np.array([[1,2,3,4]])
arr7 = np.array([[1],[2],[3],[4]])
#here their is atleast one in dimn
print(arr0.shape)
print(arr7.shape)
print(arr0*arr7)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [41]:
#multiplication table
arr0= np.array([[1,2,3,4,5,6,7,8,9,10]])
arr7 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(arr0.shape)
print(arr7.shape)
print(arr0*arr7)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [43]:
#single multiplication table
arr0= np.array([[1,2,3,4,5,6,7,8,9,10]])
arr7 = np.array([[5]])
print(arr0.shape)
print(arr7.shape)
print(arr0*arr7)

(1, 10)
(1, 1)
[[ 5 10 15 20 25 30 35 40 45 50]]


In [51]:
#aggergate function
arr8= np.array([[1,2,3,4,5,6,7,8,9,10]])
print(np.min(arr8))
print(np.mean(arr8))
print(np.max(arr8))
print(np.sum(arr8))
print(np.std(arr8))
#position of min value
print(np.argmin(arr8))

1
5.5
10
55
2.8722813232690143
0


In [54]:
arr9= np.array([[1,2,3,4],
                [5,6,7,8]])
#this is used for sum of column
print(np.sum(arr9,axis =0))
#this is to sum rows 
print(np.sum(arr9,axis =1))

[ 6  8 10 12]
[10 26]


In [66]:
#filtering
ages = np.array([[18,21,13,14,18,40],
                [39,22,34,56,12,70]])
teens = ages[ages<18]
adults = ages[(ages>=18) & (ages<=65)]
senior = ages[ages>=65]
even = ages[ages%2==0]
print(teens)
print(adults)
print(senior)
print(even)

[13 14 12]
[18 21 18 40 39 22 34 56]
[70]
[18 14 18 40 22 34 56 12 70]


In [68]:
#to preserve the shape
a = np.where(ages>=18,ages,0)
print(a)

[[18 21  0  0 18 40]
 [39 22 34 56  0 70]]


In [73]:
#random numbers
rng = np.random.default_rng()
#they r storedin 1D
print(rng.integers(low=1,high=7,size =4))
#they r storedin 2D
print(rng.integers(low=1,high=7,size =(4,2)))

[2 3 4 2]
[[3 6]
 [1 1]
 [2 2]
 [3 1]]


In [84]:
rng = np.random.default_rng()
arr = np.array([1,2,3,4])
rng.shuffle(arr)
b = rng.choice(arr,size -3)
print(arr)
print(b)

NameError: name 'size' is not defined